version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./backend:/backend
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    command: ["./main"]
